#!/bin/bash

# Create /tmp/u if it does not exist
if [ ! -d "/tmp/u" ]; then
   mkdir /tmp/u
fi

# Move all files starting with an uppercase letter to /tmp/u
find . -maxdepth 1 -type f -name '[A-Z]*' -exec mv {} /tmp/u \;
